export const FORM_TEMPLATES = [
  {
    id: "blank",
    title: "Blank Form",
    category: "General",
    description: "Start from a blank canvas and create a custom form.",
    badge: "Scratch",
    color: "#6366F1",
    fields: [],
  },
  {
    id: "contact",
    title: "Contact Form",
    category: "Business",
    description: "Collect customer inquiries, messages, and contact details.",
    badge: "Popular",
    color: "#3B82F6",
    fields: [
      { label: "Full Name", field_type: "text", is_required: true, placeholder: "John Doe" },
      { label: "Email Address", field_type: "email", is_required: true, placeholder: "john@example.com" },
      { label: "Subject", field_type: "text", is_required: true, placeholder: "Inquiry about..." },
      { label: "Message", field_type: "textarea", is_required: true, placeholder: "Type your message here..." },
    ],
  },
  {
    id: "job_application",
    title: "Job Application",
    category: "HR",
    description: "Collect applicant details, resume uploads, and experience.",
    badge: "HR",
    color: "#10B981",
    fields: [
      { label: "Full Name", field_type: "text", is_required: true, placeholder: "Jane Smith" },
      { label: "Email Address", field_type: "email", is_required: true, placeholder: "jane@example.com" },
      { label: "Phone Number", field_type: "text", is_required: true, placeholder: "+1 (555) 000-0000" },
      {
        label: "Position Applied For",
        field_type: "dropdown",
        is_required: true,
        options: ["Software Engineer", "Product Designer", "Product Manager", "Data Analyst", "Marketing Specialist"],
      },
      { label: "Years of Experience", field_type: "number", is_required: false, placeholder: "e.g. 5" },
      { label: "Portfolio URL", field_type: "text", is_required: false, placeholder: "https://portfolio.com" },
      { label: "Resume Upload", field_type: "file_upload", is_required: true, placeholder: "Upload PDF or DOCX" },
    ],
  },
  {
    id: "event_registration",
    title: "Event Registration",
    category: "Events",
    description: "Register attendees for conferences, workshops, and meetups.",
    badge: "Events",
    color: "#F59E0B",
    fields: [
      { label: "Attendee Name", field_type: "text", is_required: true, placeholder: "Alex Rivera" },
      { label: "Email Address", field_type: "email", is_required: true, placeholder: "alex@example.com" },
      {
        label: "Ticket Type",
        field_type: "dropdown",
        is_required: true,
        options: ["General Admission", "VIP Pass", "Student Pass"],
      },
      {
        label: "Dietary Requirements",
        field_type: "checkbox",
        is_required: false,
        options: ["Vegetarian", "Vegan", "Gluten-Free", "None"],
      },
      { label: "Event Date", field_type: "date", is_required: true },
    ],
  },
  {
    id: "student_registration",
    title: "Student Registration",
    category: "Education",
    description: "Enroll students for courses, departments, and academic years.",
    badge: "Education",
    color: "#8B5CF6",
    fields: [
      { label: "Student Name", field_type: "text", is_required: true, placeholder: "Emily Chen" },
      { label: "Email Address", field_type: "email", is_required: true, placeholder: "emily@university.edu" },
      {
        label: "Department",
        field_type: "dropdown",
        is_required: true,
        options: ["Computer Science", "Electrical Engineering", "Business Administration", "Design", "Mechanical Engineering"],
      },
      { label: "Enrollment Year", field_type: "number", is_required: true, placeholder: "2026" },
      { label: "Student ID Photo", field_type: "file_upload", is_required: false },
    ],
  },
  {
    id: "customer_feedback",
    title: "Customer Feedback",
    category: "Feedback",
    description: "Gather customer satisfaction ratings and feedback.",
    badge: "Feedback",
    color: "#EC4899",
    fields: [
      { label: "Customer Name", field_type: "text", is_required: false, placeholder: "Optional name" },
      { label: "Email Address", field_type: "email", is_required: false },
      { label: "Overall Satisfaction", field_type: "rating", is_required: true },
      {
        label: "Product Category",
        field_type: "dropdown",
        is_required: true,
        options: ["Usability", "Performance", "Customer Support", "Pricing", "Other"],
      },
      { label: "Detailed Feedback", field_type: "textarea", is_required: true, placeholder: "Share your experience with us..." },
    ],
  },
  {
    id: "survey",
    title: "Survey",
    category: "Research",
    description: "Conduct market research and user demographic surveys.",
    badge: "Survey",
    color: "#06B6D4",
    fields: [
      {
        label: "Age Group",
        field_type: "dropdown",
        is_required: true,
        options: ["Under 18", "18-24", "25-34", "35-44", "45+"],
      },
      {
        label: "How did you hear about us?",
        field_type: "checkbox",
        is_required: false,
        options: ["Social Media", "Search Engine", "Friend/Colleague", "Advertisement", "Other"],
      },
      { label: "Satisfaction Rating", field_type: "rating", is_required: true },
      { label: "Additional Comments", field_type: "textarea", is_required: false },
    ],
  },
  {
    id: "appointment_booking",
    title: "Appointment Booking",
    category: "Services",
    description: "Schedule client consultations, meetings, and bookings.",
    badge: "Booking",
    color: "#14B8A6",
    fields: [
      { label: "Client Name", field_type: "text", is_required: true, placeholder: "Marcus Vance" },
      { label: "Email Address", field_type: "email", is_required: true },
      { label: "Phone Number", field_type: "text", is_required: true },
      {
        label: "Service Requested",
        field_type: "dropdown",
        is_required: true,
        options: ["General Consultation", "Technical Support", "Sales Demo", "Strategy Session"],
      },
      { label: "Preferred Date", field_type: "date", is_required: true },
      { label: "Notes", field_type: "textarea", is_required: false },
    ],
  },
  {
    id: "leave_request",
    title: "Leave Request",
    category: "HR",
    description: "Employee leave application for vacation, sick, or personal time off.",
    badge: "HR",
    color: "#EF4444",
    fields: [
      { label: "Employee Name", field_type: "text", is_required: true },
      { label: "Employee Email", field_type: "email", is_required: true },
      {
        label: "Leave Type",
        field_type: "dropdown",
        is_required: true,
        options: ["Vacation", "Sick Leave", "Personal Leave", "Parental Leave", "Unpaid Leave"],
      },
      { label: "Start Date", field_type: "date", is_required: true },
      { label: "End Date", field_type: "date", is_required: true },
      { label: "Reason for Leave", field_type: "textarea", is_required: true },
    ],
  },
  {
    id: "support_request",
    title: "Support Request",
    category: "Support",
    description: "Helpdesk support ticket for reporting issues and bugs.",
    badge: "Support",
    color: "#6366F1",
    fields: [
      { label: "User Name", field_type: "text", is_required: true },
      { label: "Email Address", field_type: "email", is_required: true },
      {
        label: "Issue Priority",
        field_type: "dropdown",
        is_required: true,
        options: ["Low", "Medium", "High", "Critical"],
      },
      { label: "Issue Subject", field_type: "text", is_required: true },
      { label: "Issue Description", field_type: "textarea", is_required: true },
      { label: "Screenshot Attachment", field_type: "file_upload", is_required: false },
    ],
  },
];
